# NumPy

## Introduction

[NumPy](https://numpy.org/) is a Python library for fast (numerical) computations with arrays.  We use NumPy arrays instead of Python's lists when we need to perform fast computations with the encapsulated data.

NumPy does not come with Python, so it needs to be installed separately.  If you have a *vanilla* installation of Python, you can do it by running 

```
pip install numpy
```

from a terminal.

On the other hand, if you installed Anaconda, it should already be available.

After installation, we need to import it.  We usually give is the shortcut `np`, so that we can call its commands with `np.function` instead of `numpy.function`.  (This shortcut is the standard.)

In [1]:
import numpy as np

## Creating Arrays

### Manual Creation

We can create a NumPy array (which I will refer to simply as an array from now on), by converting a Python list, using the function `np.array`:

In [2]:
first_array = np.array([1, 2, 3, 4])

first_array

array([1, 2, 3, 4])

In [3]:
second_array = np.array([2.41, 3.11, 5.7, 11.0])

second_array

array([ 2.41,  3.11,  5.7 , 11.  ])

### Ranges

We also have `np.arange`, similar to Python's `range`, to create arrays following a pattern:

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(4, 32, 5)

array([ 4,  9, 14, 19, 24, 29])

We can also create an array with a predetermined number of entries *equally spaced* between given first and last elements using `np.linspace`:

In [7]:
np.linspace(1, 10, 25)  # array with 25 elements, starting at 1 and ending at 10

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

### Repetitions

We can create arrays of zeros and ones of a specified type as well, with `np.zeros` and `np.ones`, respectively:

In [8]:
np.zeros(10)  # 10 zeros (floats by default)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10, dtype=np.int64)  # 10 integer zeros 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros(10, dtype=bool)  # the boolean zero is False

array([False, False, False, False, False, False, False, False, False,
       False])

In [11]:
np.ones(5)  # 5 ones (floats by default)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(5, dtype=np.int64)  # 5 integer zeros 

array([1, 1, 1, 1, 1])

In [13]:
np.ones(5, dtype=bool)  # the boolean one is True

array([ True,  True,  True,  True,  True])

To create an array that repeats the same element, we can use `np.repeat` or `np.full`:

In [14]:
np.repeat(2, 7)  # seven twos

array([2, 2, 2, 2, 2, 2, 2])

In [15]:
np.full(7, 2)  # seven twos again -- note the parameters are switched!

array([2, 2, 2, 2, 2, 2, 2])

If we pass an array instead of an element to `np.repeat`, it repeats each element:

In [16]:
np.repeat(np.array([1, 2, 3]), 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

To repeat in sequence, we can use `np.tile`:

In [17]:
np.tile(np.array([1, 2, 3]), 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Random Arrays

There are a few ways to create random arrays.  (Functions for generating random data in NumPy start with `np.random`.)

To create an array with a given number of random floats between 0.0 and 1.0:

In [18]:
np.random.random(6)  # 6 random numbers between 0.0 and 1.0

array([0.11844799, 0.04665716, 0.93147435, 0.85929511, 0.11399059,
       0.4460022 ])

(Each time you run the cell above, you will get a different array.)

To create an array with a given number of integers in a range:

In [19]:
np.random.randint(1, 6, 20)  # 20 random numbers between 1 and 5 (NOT 6)

array([2, 4, 3, 2, 3, 3, 5, 2, 5, 4, 2, 1, 4, 3, 3, 4, 1, 3, 1, 2])

We can also created numbers randomly by with probabilities from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with a given average and standard deviation using `np.random.normal`.

For 20 random numbers chosen from with a normal probability curve with average 10 and standard deviation 2:

In [20]:
np.random.normal(10, 2, 20)

array([ 9.24798786,  7.27076035,  5.21395127, 12.15785616,  9.54437716,
        5.27037337, 12.15709681,  8.13338546, 11.30153987, 12.93547014,
       11.57096065, 10.07643927,  9.65587923,  8.28721224,  7.41987512,
       11.24243828, 10.29589314,  9.68437602, 11.44633702, 14.02007467])

To select random numbers from a list, we can use `np.random.choice`:

In [21]:
np.random.choice(np.array([1, 3, 7]), 10)

array([7, 7, 1, 3, 7, 1, 7, 7, 1, 3])

### Summary

| **Function** | **Description** |
|--------------|-----------------|
| `np.array`   | Converts list to array |
| `np.arange`  | Creates array range of numbers |
| `np.linspace` | Creates equally spaces numbers between given boundaries |
| `np.zeros`   | Create array of zeros (specify type with `dtype=<type>`) |
| `np.ones`    | Create array of ones (specify type with `dtype=<type>`) |
| `np.full`    | Create array of with a single element repeated |
| `np.repeat`  | Create an array repeating each element of given array |
| `np.tile`    | Create an array repeating array (in order) |

## Length

The function `len` can also be used to get lengths of arrays:

In [22]:
first_array

array([1, 2, 3, 4])

In [23]:
len(first_array)

4

For *one-dimensional array* (so arrays that do not have other arrays as elements), we can also get the length of an array from the parameter `.size`:

In [24]:
first_array.size

4

(Since `.size` is a parameter and not a method/function, we *cannot use parentheses*!)

## Operations with Arrays

If we perform an operation between a number and an array, it will perform the operation between the number and every single entry of the array:

In [25]:
first_primes = np.array([2, 3, 5, 7])

first_primes

array([2, 3, 5, 7])

In [26]:
3 + first_primes

array([ 5,  6,  8, 10])

In [27]:
3 * first_primes

array([ 6,  9, 15, 21])

In [28]:
first_primes / 2

array([1. , 1.5, 2.5, 3.5])

In [29]:
first_primes == 3

array([False,  True, False, False])

If we have two arrays of the *same size*, operations between them are performed componentwise:

In [30]:
first_squares = np.array([0, 1, 4, 9])

first_squares

array([0, 1, 4, 9])

In [31]:
first_primes + first_squares

array([ 2,  4,  9, 16])

In [32]:
first_primes * first_squares

array([ 0,  3, 20, 63])

In [33]:
first_primes ** first_squares

array([       1,        3,      625, 40353607])

In [34]:
first_primes > first_squares

array([ True,  True,  True, False])

## Some NumPy Functions

NumPy provides many functions for mathematical computations and array manipulation.  The mathematical functions are optimized for computation in arrays.  (It is *much* faster than performing the same computation individually in each entry of the array.)

For example:

In [35]:
np.sqrt(first_squares)  # square root

array([0., 1., 2., 3.])

In [36]:
np.log(first_primes)  # natural log

array([0.69314718, 1.09861229, 1.60943791, 1.94591015])

In [37]:
np.sin(np.pi * first_primes / 8 + np.pi / 3)  # sine function -- np.pi is the number pi

array([ 0.96592583,  0.79335334,  0.13052619, -0.60876143])

Here are some other useful functions:

Each of these functions takes an array as an argument and returns a single value.

| **Function**       | Description                                                          |
|--------------------|----------------------------------------------------------------------|
| `np.prod`          | Multiply all elements together                                       |
| `np.sum`           | Add all elements together                                            |
| `np.mean`          | Average of all elements                                              |
| `np.median`        | Median of all elements                                               |
| `np.std`           | Standard deviation of all elements                                   |
| `np.max`           | Maximum of all elements                                              |
| `np.min`           | Minimum of all elements                                              |

See also the [full Numpy reference](http://docs.scipy.org/doc/numpy/reference/).

## Slicing

Element extraction and slicing works just as with lists:

In [38]:
more_primes = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

more_primes

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [39]:
more_primes[3]  # fourth element

7

In [40]:
more_primes[-2]  # second to last element

23

In [41]:
more_primes[2:-3]

array([ 5,  7, 11, 13, 17])

In [42]:
more_primes[:5]

array([ 2,  3,  5,  7, 11])

In [43]:
more_primes[4:]

array([11, 13, 17, 19, 23, 29])

In [44]:
more_primes[1:8:2]

array([ 3,  7, 13, 19])

## Filtering

We can select entries of an array by giving a boolean array (or list) with `True` in the positions we want to keep and `False` in the positions we want to drop:

In [45]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [46]:
mask = [True, False, False, True, True]

mask

[True, False, False, True, True]

In [47]:
a[mask]

array([1, 4, 5])

This allows us to filter lists by conditions.  For instance, to filter the array `more_primes` for those which are less than 10, we can do:

In [48]:
more_primes[more_primes < 10]

array([2, 3, 5, 7])

## Counting

If we want to count how many elements of `more_primes` are greater than 7, we could do:

In [49]:
len(more_primes[more_primes > 7])

6

Alternatively, we can use `np.count_nonzero`.  As the name says, it counts the number of non-zero elements in an array:

In [50]:
np.count_nonzero(np.array([0, 1, 2, 0, 4, 0, 3]))

4

On the other hand, in Python the boolean `False` is (sometimes) treated as zero, while `True` is non-zero.  Hence, `np.count_nonzero` can be used to count the number of `True`'s in a boolen array:

In [51]:
np.count_nonzero(np.array([True, True, False, False, True]))

3

Thus, we could also have done (in the previous example):

In [52]:
np.count_nonzero(more_primes > 7)

6

We can also apply this idea to count how many elements match between two arrays:

In [53]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([1, 4, 3, 2, 5])

np.count_nonzero(array1 == array2)

3

## Equality of Arrays

We cannot check if two arrays are equal using `==`, as it performs the comparison componentwise:

In [54]:
array1 == array2

array([ True, False,  True, False,  True])

Instead, we must use `np.array_equal`:

In [55]:
np.array_equal(array1, array2)

False

In [56]:
np.array_equal(array1, np.array([1, 2, 3, 4, 5]))

True

## Values and Counts

It is easy to see how many times a single value occurs in an array using the tools we've already seen.

For instance, if we have

In [57]:
a = np.random.choice(np.arange(5), 10)
a

array([0, 2, 1, 0, 0, 1, 3, 4, 4, 0])

and we want to count how many threes we have, we can simply do:

In [58]:
np.count_nonzero(a == 3)

1

But, sometimes we want to see how many occurrences we have for *each value* of the array, not just a single value.  For that, we can use [np.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html).  

By default, it simply gives the unique values in the array, *sorted*.  This can be useful when we are not sure what values actually occur in a array, e.g., when we create an array randomly:

In [59]:
# 10 values between 0 and 99
b = np.random.randint(0, 100, 10)
b

array([ 2, 12,  0, 63,  0, 62, 61, 47, 75, 12])

In [60]:
np.unique(b)

array([ 0,  2, 12, 47, 61, 62, 63, 75])

With our previous array `a`:

In [61]:
np.unique(a)

array([0, 1, 2, 3, 4])

To actually get how many times each unique value occurs, we need the optional argument `return_counts=True`

In [62]:
np.unique(a, return_counts=True)

(array([0, 1, 2, 3, 4]), array([4, 2, 1, 1, 2]))

The output is now two arrays: the first one is the same, the unique values *sorted*, while the second array contains the counts for each *respective* unique value.

As another example:

In [63]:
# 100 values between 0 and 9
c = np.random.randint(0, 10, 100)

values, counts = np.unique(c, return_counts=True)

for value, count in zip(values, counts):
    print(f"The value {value} occurs {count:>2} times.")

The value 0 occurs  6 times.
The value 1 occurs  5 times.
The value 2 occurs  7 times.
The value 3 occurs 11 times.
The value 4 occurs 13 times.
The value 5 occurs 10 times.
The value 6 occurs 21 times.
The value 7 occurs 10 times.
The value 8 occurs 12 times.
The value 9 occurs  5 times.


## Arrays of Strings

We can also perform operations with arrays of strings:

In [64]:
string_array = np.array(["A", "bb", "CcC", "ddDD"])
string_array

array(['A', 'bb', 'CcC', 'ddDD'], dtype='<U4')

NumPy functions for strings start with `np.char`.

For instance, to convert to lower case:

In [65]:
np.char.lower(string_array)

array(['a', 'bb', 'ccc', 'dddd'], dtype='<U4')

To convert to upper case:

In [66]:
np.char.upper(string_array)

array(['A', 'BB', 'CCC', 'DDDD'], dtype='<U4')

We can replace occurrences of `C` with `X` in the strings:

In [67]:
np.char.replace(string_array, "C", "X")

array(['A', 'bb', 'XcX', 'ddDD'], dtype='<U4')

### Other Functions

Here are some useful functions for strings,

Each of these functions takes an array of strings and returns an array.

| **Function**        | **Description**                                              |
|---------------------|--------------------------------------------------------------|
| `np.char.lower`     | Lowercase each element                                       |
| `np.char.upper`     | Uppercase each element                                       |
| `np.char.strip`     | Remove spaces at the beginning or end of each element        |
| `np.char.isalpha`   | Whether each element is only letters (no numbers or symbols) |
| `np.char.isnumeric` | Whether each element is only numeric (no letters)  |


Each of these functions takes both an array of strings and a *search string*; each returns an array.

| **Function**         | **Description**                                                                  |
|----------------------|----------------------------------------------------------------------------------|
| `np.char.count`      | Count the number of times a search string appears among the elements of an array |
| `np.char.find`       | The position within each element that a search string is found first             |
| `np.char.rfind`      | The position within each element that a search string is found last              |
| `np.char.startswith` | Whether each element starts with the search string                               |

You can find a lot more about string functions with `help(np.char)`.

## Examples

### Example: Converting Temperatures

As a simple application, let's convert an array of temperatures in Fahrenheit to Celsius.

First, let's create a randomize array of temperatures that between $T_0 - \Delta$ and $T_0 + \Delta$, where $T_0$ is some base temperature and $\Delta$ is some temperature variation.  (Let's set them to $60$ and $40$ respectively.)

In [68]:
base_temperature = 60  # T_0
variation = 40  # Delta
number_of_temps = 30

temperatures = base_temperature - variation + 2 * variation * np.random.random(number_of_temps)

temperatures

array([80.7236593 , 20.33484728, 52.68040663, 26.89913425, 70.12779349,
       20.32530087, 79.87284465, 70.87106029, 85.00069329, 48.4786461 ,
       29.84129781, 94.32923317, 67.91863786, 89.24303695, 88.03396116,
       53.20263649, 41.83617387, 41.58451032, 41.87508779, 62.28580301,
       66.79766944, 97.47998568, 96.46039284, 98.3168157 , 79.98981846,
       63.37781431, 64.4483931 , 46.46706998, 83.06306619, 29.17748606])

The formula to convert to Celsius is:

$$
\text{Temp in Celsius} = \frac{5}{9} \cdot \left( \text{Temp in Fahrenheit} - 32 \right)
$$

So, we can covert with:

In [69]:
temperatures_celsius = 5 / 9 * (temperatures - 32)

temperatures_celsius

array([27.06869961, -6.4806404 , 11.4891148 , -2.83381431, 21.18210749,
       -6.48594396, 26.59602481, 21.59503349, 29.44482961,  9.15480339,
       -1.199279  , 34.62735176, 19.95479881, 31.80168719, 31.12997842,
       11.7792425 ,  5.46454104,  5.32472796,  5.48615988, 16.82544612,
       19.33203858, 36.37776982, 35.81132936, 36.84267539, 26.66101025,
       17.43211906, 18.02688506,  8.0372611 , 28.36837011, -1.5680633 ])

We can round to two decimal places with `np.round`:

In [70]:
temperatures_celsius = np.round(5 / 9 * (temperatures - 32), 2)

temperatures_celsius

array([27.07, -6.48, 11.49, -2.83, 21.18, -6.49, 26.6 , 21.6 , 29.44,
        9.15, -1.2 , 34.63, 19.95, 31.8 , 31.13, 11.78,  5.46,  5.32,
        5.49, 16.83, 19.33, 36.38, 35.81, 36.84, 26.66, 17.43, 18.03,
        8.04, 28.37, -1.57])

### Example: Checking a Trigonometric Identity

It is a well-know theorem that for any real number $x$, we have that 

$$
\cos^2(x) + \sin^2(x) = 1.
$$

Let's check this with some concrete examples!

We first create a large set of numbers to try.  Since the values of sine and cosine are periodic of period $2 \pi$ (in other words, $\cos(x + 2\pi) = \cos(x)$ and $\sin(x + 2\pi) = \sin(x)$), we can simply check it for several numbers between $0$ and $2\pi$.

In [71]:
number_of_tests = 10 ** 5  # one hundred thousand tests!
test_cases = 2 * np.pi * np.random.random(number_of_tests)

Now we compute the sine and cosines, square them, and then add them:

In [72]:
result = np.cos(test_cases) ** 2 + np.sin(test_cases) ** 2

If the theorem is really true, we should get `number_of_test` ones in `result`.  So, let's check:

In [73]:
np.count_nonzero(result == 1)

77530

Oh-oh, something is not quite right.  Either our theorem is not true, or there is something fishy here.

Let's inspect the first 10 elements for which we do not get one:

In [74]:
result[result != 1][:10]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

What?  They seem to be one...  Do we need 1.0 (float) instead of 1 (int)?

In [75]:
np.count_nonzero(result == 1.0)

77530

In [76]:
result[result != 1.0][:10]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Apparently not.  *The reason is that floats have approximation errors, so it is hard to tell when two floats are actually equal!*

So, let's simply check if the result is really *close* to one, say the difference less than $10^{-6} = 0.000001$:

In [77]:
margin_of_error = 10 ** (-9)
np.count_nonzero(np.abs(result - 1) < margin_of_error)

100000

Ah, so *all* of the results were within our margin of error.

### Example: Leibniz's formula for $\pi$

**Acknowledgment:** This is based in an example from [Computational and Inferential Thinking: The Foundations of Data Science](https://inferentialthinking.com/chapters/intro.html), by A. Adhikari, J. DeNero, D. Wagner.

[Gottfried Wilhelm Leibniz](https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz) 
(1646 - 1716) discovered the following formula for $\pi$ as an infinite sum of fractions:

$$\pi = 4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots\right)$$

(For the math inclined: this is related to the fact that $\arctan(1) = \pi/4$.  You can then use the [Taylor series](https://en.wikipedia.org/wiki/Taylor_series) for $\arctan$.)

By stopping after a finite number steps we get an *approximation* of $\pi$, with better approximations for larger number of terms.  Let's check this approximation using the first $5{,}000$ terms!

$$4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots + \frac{1}{9997} - \frac{1}{9999} \right)$$

We will add the postiive terms, subtract the negative terms, and then multiply by $4$:

$$4 \cdot \left( \left(1 + \frac{1}{5} + \frac{1}{9} + \dots + \frac{1}{9997} \right) - \left(\frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \dots + \frac{1}{9999} \right) \right)$$

Let's start by making an array with the positive denominators:

In [78]:
positive_term_denominators = np.arange(1, 9998, 4)

To get the terms, we need to invert them:

In [79]:
positive_terms = 1 / positive_term_denominators

We could something similar for the negative terms, but it is a bit simpler:

In [80]:
negative_term_denominators = 2 + positive_term_denominators
negative_terms = 1 / negative_term_denominators

Now we can just add the terms, subtract the two, and multiply by $4$:

In [81]:
leibniz_pi = 4 * (np.sum(positive_terms) - np.sum(negative_terms))
leibniz_pi

3.141392653591792

Let's compare it to the numerical approximation of $\pi$ from NumPy:

In [82]:
np.pi

3.141592653589793

In [83]:
np.pi - leibniz_pi

0.00019999999800113244

## Efficiency

### Avoid Loops

The "usual" way to compute something like that would be to use loops.  Note that we have:


$$\pi = 4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \cdots + (-1)^i \frac{1}{2i + 1} + \cdots \right)$$

where $(-1)^i \dfrac{1}{2i + 1}$ is the $(i + 1)$-th term of the sum.  (The sum starts with $i=0$.)

Let's compute it with a loop (as would be natural):

In [84]:
result = 0
for i in range(5000):
    sign = (-1) ** i
    result += sign / (2 * i + 1)
4 * result

3.141392653591791

This, of course, it also works!  But let's time it:

In [85]:
%%timeit
res = 0
for i in range(5000):
    sign = (-1) ** i
    res += sign / (2 * i + 1)
4 * res

358 µs ± 3.21 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Now, let's look at the time for the computation using NumPy (i.e., "vectorized" computations):

In [86]:
%%timeit
positive_denominators = np.arange(1, 9998, 4)
4 * ((1 / positive_denominators).sum() - (1 / (positive_denominators + 2)).sum())

7.82 µs ± 94.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


As you can see, the second method is *a lot* more efficient!  

On the other hand, the second memory uses more memory, as it has to create large arrays.  (In my test it used over 6 times the amount of memory as the first, which uses very little memory.  So, it is still not bad!)

And of course, even though the first method was about 50 times slower, it makes virtually no difference in this example!  But it does make a difference in more complex examples.

So: **avoid using loops and use NumPy's vectorized functions instead whenever possible!**

### Do Not Append to Array

Here is another common mistake: although we can add elements to arrays using `np.append`, this operation is relatively slow.  Instead, try to initialize your array with zeros (of the right type), and then override its values.

For instance: suppose you want to choose ten random values between 0.0 and 1.0, find the average and add the result to an array *one hundred thousand times*.  We could do:

In [87]:
%%time

number_of_repetitions = 100_000

results = np.array([])

for i in range(number_of_repetitions):
    results = np.append(results, np.mean(np.random.random(10)))

results[:10]

CPU times: user 977 ms, sys: 134 µs, total: 977 ms
Wall time: 978 ms


array([0.46009249, 0.38422247, 0.62830152, 0.33825051, 0.5558268 ,
       0.43837151, 0.59652821, 0.4777373 , 0.54116138, 0.43855052])

Instead, it is a lot more efficient to initialize the an array to the correct size (with zeros, for instance) and data type, and then overwrite the entries.  

In [88]:
%%time

number_of_repetitions = 100_000

results = np.zeros(number_of_repetitions)

for i in range(number_of_repetitions):
    results[i] = np.mean(np.random.random(10))
    
results[:10]

CPU times: user 224 ms, sys: 49.1 ms, total: 273 ms
Wall time: 221 ms


array([0.58252952, 0.59665626, 0.45658924, 0.44129525, 0.62756876,
       0.60933696, 0.49136511, 0.46356053, 0.44686351, 0.501762  ])

As one can clearly see, this second method is a lot faster!

If you are familiar with [list comprehensions](https://docs.python.org/2/tutorial/datastructures.html#list-comprehensions) in Python, the previous method is just as efficient as:

In [89]:
%%time 

number_of_repetitions = 100000

results = np.array([np.mean(np.random.random(10)) for i in range(number_of_repetitions)])

results[:10]

CPU times: user 257 ms, sys: 85.5 ms, total: 342 ms
Wall time: 237 ms


array([0.40314698, 0.67488771, 0.53110525, 0.41376086, 0.57357961,
       0.54998524, 0.53873054, 0.45462466, 0.6212739 , 0.45074004])

## More Examples

### Example: Computing Grades

We've only used *one-dimensional* arrays so far.  Now suppose we have an array with arrays as its elements, a *two-dimensional array*.  Each entry is an array with grades for a student.

For example, lets create six grades for ten students (so an array with 10 arrays of 6 grades each) with normal distribution of average $80$ and standard deviation $15$.  (We might get grades over $100$.  Let's just assume that they were obtained by extra-credit.)

In [90]:
grades = np.array([np.round(np.random.normal(80, 15, 6)).astype(int) for i in range(10)])

grades

array([[ 75,  82,  85,  86,  92,  78],
       [100,  88,  95,  81,  80, 101],
       [ 86,  97,  64, 106,  70,  70],
       [ 62,  70, 105,  93,  52, 109],
       [ 96, 102,  67,  81,  76,  63],
       [ 72,  70,  87,  98,  92,  84],
       [ 76,  73,  74,  75,  73,  68],
       [ 86,  73,  94,  81,  73,  87],
       [ 85,  66, 101,  94,  81,  77],
       [ 75, 106, 110,  87,  85,  78]])

Suppose that the first three grades are homework grades, with weight of $10\%$ each, the next two are midterm grades, with weights of $20\%$ each, and the last is the final grade, with weight $30\%$.  

**Goal:** We want to compute the students averages.

First, let's create an array with the weights:

In [91]:
weights = np.array([0.1, 0.1, 0.1, 0.2, 0.2, 0.3])

Now, we want to multiply each grade by its weight.  Since the arrays in `grades` have the same length as `weight`, we can do it directly!

In [92]:
weighted_grades = grades * weights

weighted_grades

array([[ 7.5,  8.2,  8.5, 17.2, 18.4, 23.4],
       [10. ,  8.8,  9.5, 16.2, 16. , 30.3],
       [ 8.6,  9.7,  6.4, 21.2, 14. , 21. ],
       [ 6.2,  7. , 10.5, 18.6, 10.4, 32.7],
       [ 9.6, 10.2,  6.7, 16.2, 15.2, 18.9],
       [ 7.2,  7. ,  8.7, 19.6, 18.4, 25.2],
       [ 7.6,  7.3,  7.4, 15. , 14.6, 20.4],
       [ 8.6,  7.3,  9.4, 16.2, 14.6, 26.1],
       [ 8.5,  6.6, 10.1, 18.8, 16.2, 23.1],
       [ 7.5, 10.6, 11. , 17.4, 17. , 23.4]])

Now we have to add all the grades for each student.  We can try `np.sum`:

In [93]:
np.sum(weighted_grades)

827.9

That is not what we want!  It added all grades, from all students, together!

We want to just add the arrays in `weighted_grades`.  We can do that by specifying the argument `axis=1`.  (In reality `axis=1` implies we are adding entries from a row.  Using `axis=0` would add entries in a column.)

In [94]:
averages = np.sum(weighted_grades, axis=1)

averages

array([83.2, 90.8, 80.9, 85.4, 76.8, 86.1, 72.3, 82.2, 83.3, 86.9])

(As expected, the averages are pretty close to $80$.)

#### Dropping a Homework Grade

What if I want to drop the lowest homework score?  

Then, the weight of each homework grade must be $15\%$ instead of $10\%$, so let's adjust the weights:

In [95]:
new_weights = np.array([0.15, 0.15, 0.15, 0.2, 0.2, 0.3])

new_weights

array([0.15, 0.15, 0.15, 0.2 , 0.2 , 0.3 ])

We can again get weighted grades by simply multiplying.

In [96]:
new_weighted_grades = grades * new_weights

Now, we want to add the grades, but drop the lowest homework score.  So, let's start my getting simply the weighted homework grades by *slicing* `weighted_grades`:

In [97]:
new_weighted_grades

array([[11.25, 12.3 , 12.75, 17.2 , 18.4 , 23.4 ],
       [15.  , 13.2 , 14.25, 16.2 , 16.  , 30.3 ],
       [12.9 , 14.55,  9.6 , 21.2 , 14.  , 21.  ],
       [ 9.3 , 10.5 , 15.75, 18.6 , 10.4 , 32.7 ],
       [14.4 , 15.3 , 10.05, 16.2 , 15.2 , 18.9 ],
       [10.8 , 10.5 , 13.05, 19.6 , 18.4 , 25.2 ],
       [11.4 , 10.95, 11.1 , 15.  , 14.6 , 20.4 ],
       [12.9 , 10.95, 14.1 , 16.2 , 14.6 , 26.1 ],
       [12.75,  9.9 , 15.15, 18.8 , 16.2 , 23.1 ],
       [11.25, 15.9 , 16.5 , 17.4 , 17.  , 23.4 ]])

We want (all rows and) the first three columns.  In a two-dimensional array, we can get slices of rows and columns, giving them *in this order* (slice for the rows first, then slice for the columns), separated by a comma:

In [98]:
new_weighted_hws = new_weighted_grades[:, :3]  # all rows [:], and first three columns: [:3]

new_weighted_hws

array([[11.25, 12.3 , 12.75],
       [15.  , 13.2 , 14.25],
       [12.9 , 14.55,  9.6 ],
       [ 9.3 , 10.5 , 15.75],
       [14.4 , 15.3 , 10.05],
       [10.8 , 10.5 , 13.05],
       [11.4 , 10.95, 11.1 ],
       [12.9 , 10.95, 14.1 ],
       [12.75,  9.9 , 15.15],
       [11.25, 15.9 , 16.5 ]])

Now, I need the minimum *of the rows*.  If I simply use `np.min`:

In [99]:
np.min(new_weighted_hws)

9.299999999999999

Again, it computes the minimum of all entries in the array.  And again, we solve this by using the optional argument `axis=1`, just like with `np.sum`:

In [100]:
min_hw_scores = np.min(new_weighted_hws, axis=1)

min_hw_scores

array([11.25, 13.2 ,  9.6 ,  9.3 , 10.05, 10.5 , 10.95, 10.95,  9.9 ,
       11.25])

Now, I can simply subtract this lowest weighted homework score from the sum of all weighted grades:

In [101]:
new_averages = np.sum(new_weighted_grades, axis=1) - min_hw_scores

new_averages

array([84.05, 91.75, 83.65, 87.95, 80.  , 87.05, 72.5 , 83.9 , 86.  ,
       90.2 ])

### Example: Compound Interest

Let's now create an array that has the monthly balances from a savings account.

If

$$
\begin{align*}
  P &= \text{principal (or initial amount)}, \\
  r &= \text{interest rate (APR) as a percent}, \\
  t &= \text{number of days}, \\
  F &= \text{final value (after $t$ days)},
\end{align*}
$$

then, starting with $P$ dollars, in a savings account with rate of $r$, after $t$ days, we will have

$$
F = P \cdot \left( {1 + \frac{r}{100 \cdot 365}} \right)^t
$$

Let's assume we have $2{,}000$ dollars in an account with $3\%$ rate.

In [102]:
P = 2000  # principal (initial amount)
r = 3  # interest rate (in %)

As will see, it will also be handy to save

$$
1 + \frac{r}{100 \cdot 365}
$$

in a variable, which we will call `factor`:

In [103]:
factor = 1 + r / (100 * 365)

Now, lets make an array with the (approximate) monthly balances for the next $3$ years (so $36$ months).  Let's round the number of days in a month to $30$.

We can start by creating an array with

```python
[1, factor ** 30, factor ** 60, factor ** 90, ..., factor ** 1080]
```

as then we only need to multiply this array by $P$.

First, though, we create the exponents

```python
[0, 30, 60, 90, ... , 1080]
```

To make the code more flexible, let's use a variable for the number of months:

In [104]:
months = 36

Now the exponents:

In [105]:
exponents = np.arange(0, months * 30 + 1, 30)  # NOTE THE "+1" to include the last term!

exponents

array([   0,   30,   60,   90,  120,  150,  180,  210,  240,  270,  300,
        330,  360,  390,  420,  450,  480,  510,  540,  570,  600,  630,
        660,  690,  720,  750,  780,  810,  840,  870,  900,  930,  960,
        990, 1020, 1050, 1080])

Then, we produce

```python
[1, factor ** 30, factor ** 60, factor ** 90, ..., factor ** 1080]
```

In [106]:
factors = factor ** exponents

factors

array([1.        , 1.00246869, 1.00494348, 1.00742438, 1.0099114 ,
       1.01240457, 1.01490388, 1.01740937, 1.01992104, 1.02243892,
       1.02496301, 1.02749333, 1.03002989, 1.03257272, 1.03512183,
       1.03767723, 1.04023894, 1.04280697, 1.04538134, 1.04796207,
       1.05054917, 1.05314265, 1.05574254, 1.05834884, 1.06096158,
       1.06358077, 1.06620643, 1.06883857, 1.0714772 , 1.07412235,
       1.07677403, 1.07943226, 1.08209705, 1.08476841, 1.08744637,
       1.09013095, 1.09282215])

Now, we just multiply by $P$ (rounding to 2 decimals):

In [107]:
balances = np.round(P * factors, 2)

balances

array([2000.  , 2004.94, 2009.89, 2014.85, 2019.82, 2024.81, 2029.81,
       2034.82, 2039.84, 2044.88, 2049.93, 2054.99, 2060.06, 2065.15,
       2070.24, 2075.35, 2080.48, 2085.61, 2090.76, 2095.92, 2101.1 ,
       2106.29, 2111.49, 2116.7 , 2121.92, 2127.16, 2132.41, 2137.68,
       2142.95, 2148.24, 2153.55, 2158.86, 2164.19, 2169.54, 2174.89,
       2180.26, 2185.64])

So, after $10$ months, the balance is:

In [108]:
balances[10]

2049.93

####  Adding Deposits

Let's now assume that we deposit the same amount very month (i.e., every $30$ days) in our savings account. Let's call this amount $A$ and choose, say, $\$150$:

In [109]:
A = 150

The problem now is that I cannot just add $A$ every month, since after that money is in our account, it also affects the interest paid!

What we need to add to `balances` is in fact:

```python
[0, 
 A, 
 A + A * factor ** 30, 
 A + A * factor ** 30 + A * factor ** 60, 
 A + A * factor ** 30 + A * factor ** 60 + A * factor ** 90, ...].
```

so we account for the interest for each deposit.

Let's start by producing

```python
[A, 
 A * factor ** 30,
 A * factor ** 60, 
 A * factor ** 90, ...]
```

with length equal to the total number of months *minus 1*.  Let's again round as well:

In [110]:
deposits = np.round(A * factors[:-1], 2)

deposits

array([150.  , 150.37, 150.74, 151.11, 151.49, 151.86, 152.24, 152.61,
       152.99, 153.37, 153.74, 154.12, 154.5 , 154.89, 155.27, 155.65,
       156.04, 156.42, 156.81, 157.19, 157.58, 157.97, 158.36, 158.75,
       159.14, 159.54, 159.93, 160.33, 160.72, 161.12, 161.52, 161.91,
       162.31, 162.72, 163.12, 163.52])

Now we want to go from our `deposits`

```python
[A, 
 A * factor ** 30, 
 A * factor ** 60, 
 A * factor ** 90, ...]
```

to

```python
[A, 
 A + A * factor ** 30, 
 A + A * factor ** 30 + A * factor ** 60, 
 A + A * factor ** 30 + A * factor ** 60 + A * factor ** 90, ...].
```

That is simply the *cumulative sum* of the array!  The cumulative sum of $(x_1, x_2, x_3, x_4)$ is simply

$$
\begin{align*}
 (&x_1, \\
&x_1 + x_2, \\
&x_1 + x_2 + x_3\\
&x_1 + x_2 + x_3 + x_4).
\end{align*}
$$

Fortunately NumPy can do that for us with the function [np.cumsum](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html).  

For instance `np.cumsum(np.array([1, 2, 3, 4]))` gives `[1, 3, 6, 10]`.

In [111]:
deposits = np.cumsum(deposits)

deposits

array([ 150.  ,  300.37,  451.11,  602.22,  753.71,  905.57, 1057.81,
       1210.42, 1363.41, 1516.78, 1670.52, 1824.64, 1979.14, 2134.03,
       2289.3 , 2444.95, 2600.99, 2757.41, 2914.22, 3071.41, 3228.99,
       3386.96, 3545.32, 3704.07, 3863.21, 4022.75, 4182.68, 4343.01,
       4503.73, 4664.85, 4826.37, 4988.28, 5150.59, 5313.31, 5476.43,
       5639.95])

Finally, we need to add a zero at the beginning and add the results to our previous `balances`:

In [112]:
deposits = np.append(0, deposits)

deposits

array([   0.  ,  150.  ,  300.37,  451.11,  602.22,  753.71,  905.57,
       1057.81, 1210.42, 1363.41, 1516.78, 1670.52, 1824.64, 1979.14,
       2134.03, 2289.3 , 2444.95, 2600.99, 2757.41, 2914.22, 3071.41,
       3228.99, 3386.96, 3545.32, 3704.07, 3863.21, 4022.75, 4182.68,
       4343.01, 4503.73, 4664.85, 4826.37, 4988.28, 5150.59, 5313.31,
       5476.43, 5639.95])

In [113]:
new_balances = balances + deposits

new_balances

array([2000.  , 2154.94, 2310.26, 2465.96, 2622.04, 2778.52, 2935.38,
       3092.63, 3250.26, 3408.29, 3566.71, 3725.51, 3884.7 , 4044.29,
       4204.27, 4364.65, 4525.43, 4686.6 , 4848.17, 5010.14, 5172.51,
       5335.28, 5498.45, 5662.02, 5825.99, 5990.37, 6155.16, 6320.36,
       6485.96, 6651.97, 6818.4 , 6985.23, 7152.47, 7320.13, 7488.2 ,
       7656.69, 7825.59])

Now, after $10$ months, the balance is:

In [114]:
new_balances[10]

3566.71

## Comments, Suggestions, Corrections

Please send your comments, suggestions, and corrections to lfinotti@utk.edu.